name: Download M3U files

# Runs daily at 03:00 Beijing Time (UTC+8). Converted to UTC this is 19:00 previous day.
on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Ensure repository root writable
        run: echo "Saving downloaded files to repository root"

      - name: Download eng.m3u and fra.m3u (curl)
        run: |
          set -eo pipefail

          curl -fsSL "https://iptv.hacks.tools/api/download?url=https://live.hacks.tools/iptv/languages/eng.m3u" -o eng.m3u >/dev/null 2>&1 || echo "[Download] WARNING: eng.m3u download failed"
          curl -fsSL "https://iptv.hacks.tools/api/download?url=https://live.hacks.tools/iptv/languages/fra.m3u" -o fra.m3u >/dev/null 2>&1 || echo "[Download] WARNING: fra.m3u download failed"

      - name: Commit and push changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add eng.m3u fra.m3u || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update eng.m3u and fra.m3u from live.hacks.tools"
            git push
          fi

      - name: Upload files as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: m3u-files
          path: |
            eng.m3u
            fra.m3u